// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import (
	"context"
	"github.com/ascenmmo/websocket-server/pkg/api"
	"github.com/ascenmmo/websocket-server/pkg/api/types"
)

type serverServerSettings struct {
	svc               api.ServerSettings
	getConnectionsNum ServerSettingsGetConnectionsNum
	healthCheck       ServerSettingsHealthCheck
	getServerSettings ServerSettingsGetServerSettings
	createRoom        ServerSettingsCreateRoom
}

type MiddlewareSetServerSettings interface {
	Wrap(m MiddlewareServerSettings)
	WrapGetConnectionsNum(m MiddlewareServerSettingsGetConnectionsNum)
	WrapHealthCheck(m MiddlewareServerSettingsHealthCheck)
	WrapGetServerSettings(m MiddlewareServerSettingsGetServerSettings)
	WrapCreateRoom(m MiddlewareServerSettingsCreateRoom)

	WithTrace()
	WithLog()
}

func newServerServerSettings(svc api.ServerSettings) *serverServerSettings {
	return &serverServerSettings{
		createRoom:        svc.CreateRoom,
		getConnectionsNum: svc.GetConnectionsNum,
		getServerSettings: svc.GetServerSettings,
		healthCheck:       svc.HealthCheck,
		svc:               svc,
	}
}

func (srv *serverServerSettings) Wrap(m MiddlewareServerSettings) {
	srv.svc = m(srv.svc)
	srv.getConnectionsNum = srv.svc.GetConnectionsNum
	srv.healthCheck = srv.svc.HealthCheck
	srv.getServerSettings = srv.svc.GetServerSettings
	srv.createRoom = srv.svc.CreateRoom
}

func (srv *serverServerSettings) GetConnectionsNum(ctx context.Context, token string) (countConn int, exists bool, err error) {
	return srv.getConnectionsNum(ctx, token)
}

func (srv *serverServerSettings) HealthCheck(ctx context.Context, token string) (exists bool, err error) {
	return srv.healthCheck(ctx, token)
}

func (srv *serverServerSettings) GetServerSettings(ctx context.Context, token string) (settings types.Settings, err error) {
	return srv.getServerSettings(ctx, token)
}

func (srv *serverServerSettings) CreateRoom(ctx context.Context, token string, createRoom types.CreateRoomRequest) (err error) {
	return srv.createRoom(ctx, token, createRoom)
}

func (srv *serverServerSettings) WrapGetConnectionsNum(m MiddlewareServerSettingsGetConnectionsNum) {
	srv.getConnectionsNum = m(srv.getConnectionsNum)
}

func (srv *serverServerSettings) WrapHealthCheck(m MiddlewareServerSettingsHealthCheck) {
	srv.healthCheck = m(srv.healthCheck)
}

func (srv *serverServerSettings) WrapGetServerSettings(m MiddlewareServerSettingsGetServerSettings) {
	srv.getServerSettings = m(srv.getServerSettings)
}

func (srv *serverServerSettings) WrapCreateRoom(m MiddlewareServerSettingsCreateRoom) {
	srv.createRoom = m(srv.createRoom)
}

func (srv *serverServerSettings) WithTrace() {
	srv.Wrap(traceMiddlewareServerSettings)
}

func (srv *serverServerSettings) WithLog() {
	srv.Wrap(loggerMiddlewareServerSettings())
}
