// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import (
	"context"
	"github.com/ascenmmo/websocket-server/pkg/restconnection"
	"github.com/ascenmmo/websocket-server/pkg/restconnection/types"
	"github.com/google/uuid"
)

type ServerSettingsGetConnectionsNum func(ctx context.Context, token string) (countConn int, exists bool, err error)
type ServerSettingsHealthCheck func(ctx context.Context, token string) (exists bool, err error)
type ServerSettingsGetServerSettings func(ctx context.Context, token string) (settings types.Settings, err error)
type ServerSettingsCreateRoom func(ctx context.Context, token string, createRoom types.CreateRoomRequest) (err error)
type ServerSettingsGetGameResults func(ctx context.Context, token string) (gameConfigResults []types.GameConfigResults, err error)
type ServerSettingsSetNotifyServer func(ctx context.Context, token string, id uuid.UUID, url string) (err error)

type MiddlewareServerSettings func(next restconnection.ServerSettings) restconnection.ServerSettings

type MiddlewareServerSettingsGetConnectionsNum func(next ServerSettingsGetConnectionsNum) ServerSettingsGetConnectionsNum
type MiddlewareServerSettingsHealthCheck func(next ServerSettingsHealthCheck) ServerSettingsHealthCheck
type MiddlewareServerSettingsGetServerSettings func(next ServerSettingsGetServerSettings) ServerSettingsGetServerSettings
type MiddlewareServerSettingsCreateRoom func(next ServerSettingsCreateRoom) ServerSettingsCreateRoom
type MiddlewareServerSettingsGetGameResults func(next ServerSettingsGetGameResults) ServerSettingsGetGameResults
type MiddlewareServerSettingsSetNotifyServer func(next ServerSettingsSetNotifyServer) ServerSettingsSetNotifyServer
