// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package wsGameServer

type fallbackServerSettings interface {
	GetConnectionsNum(err error) bool
	HealthCheck(err error) bool
	GetServerSettings(err error) bool
	CreateRoom(err error) bool
	GetGameResults(err error) bool
	SetNotifyServer(err error) bool
}
